name: lucene-solr
branches: [ master ]
build:
    runs_on: java1.11
    steps:

      - name: Run 
        run: |
          mkdir -p lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT 

          cp lucene/core/build/packaging/lucene-core-9.0.0-SNAPSHOT.jar lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT
          cp lucene/facet/build/packaging/lucene-facet-9.0.0-SNAPSHOT.jar lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT 
          cp lucene/queries/build/packaging/lucene-queries-9.0.0-SNAPSHOT.jar lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT 
          cp lucene/analysis/common/build/packaging/lucene-analysis-common-9.0.0-SNAPSHOT.jar lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT 
          cp lucene/queryparser/build/packaging/lucene-queryparser-9.0.0-SNAPSHOT.jar lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT  
          cp lucene/expressions/build/packaging/lucene-expressions-9.0.0-SNAPSHOT.jar lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT 

          cp -R lucene/demo/build/classes/java/main/org lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT 
          cd lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT
          cat > Manifest.txt <<EOF
          Main-Class: org.apache.lucene.demo.SearchFiles
          Class-Path: lucene-core-9.0.0-SNAPSHOT.jar lucene-facet-9.0.0-SNAPSHOT.jar lucene-queries-9.0.0-SNAPSHOT.jar lucene-analysis-common-9.0.0-SNAPSHOT.jar lucene-queryparser-9.0.0-SNAPSHOT.jar lucene-expressions-9.0.0-SNAPSHOT.jar
          Manifest-Version: 1.0
          EOF

          jar cfm lucene-demo-9.0.0-dosearch.jar Manifest.txt org/ 

          rm Manifest.txt
          cat > Manifest.txt <<EOF
          Main-Class: org.apache.lucene.demo.IndexFiles
          Class-Path: lucene-core-9.0.0-SNAPSHOT.jar lucene-facet-9.0.0-SNAPSHOT.jar lucene-queries-9.0.0-SNAPSHOT.jar lucene-analysis-common-9.0.0-SNAPSHOT.jar lucene-queryparser-9.0.0-SNAPSHOT.jar lucene-expressions-9.0.0-SNAPSHOT.jar
          Manifest-Version: 1.0
          EOF

          jar cfm lucene-demo-9.0.0-doindex.jar Manifest.txt org/ 


d4tasks:  
 
  - name: Do_SearchFiles
    which_main_class: org/apache/lucene/demo/SearchFiles
    jar: /lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT/lucene-demo-9.0.0-dosearch.jar
    classes: /lucene/demo/build/classes
    exclusions: 
      java/applet/.*,
      java/awt/.*,
      java/beans/.*,
      java/math/.*,
      java/net/.*,
      java/rmi/.*,
      java/sql/.*, 
      java/text/.*,
      java/util/concurrent/atomic/.*,
      java/util/jar/.*,
      java/util/logging/.*,
      java/util/prefs/.*,
      java/util/regex/.*,
      java/util/spi/.*,
      java/util/zip/.*,
      java/time/.*,
      javax/.*,
      sun/.*,
      sunw/.*,
      com/sun/.*,
      com/ibm/.*,
      com/apple/.*,
      com/oracle/.*,
      apple/.*,
      org/xml/.*,
      jdbm/.*,
      org/netbeans/.*,
      org/openide/.*,
      org/apache/xerces/.*,
      org/apache/batik/.*,
      org/apache/jasper/.*,
      dalvik/.*,
      apple/.*,
      jdk/.*,
      org/omg/.*,
      org/w3c/.*,
      org/apache/lucene/util/packed/BulkOperationPacked.*,
      javafx/.*,
      org/jcp/.*,
      oracle/jrockit/.*,
      com/jrockit/.*,
      oracle/jvm/.*,
      org/apache/http/.*,
      org/eclipse/.*,
      se/hirt/.*,
      org/osgi/.*
    
  - name: Do_IndexFiles
    which_main_class: org/apache/lucene/demo/IndexFiles
    jar: /lucene/demo/build/packaging/lucene-demo-9.0.0-SNAPSHOT/lucene-demo-9.0.0-doindex.jar
    classes: /lucene/demo/build/classes
    exclusions:  
      java/applet/.*,
      java/awt/.*,
      java/beans/.*,
      java/math/.*, 
      java/net/.*,
      java/rmi/.*,
      java/sql/.*,
      java/text/.*,
      java/util/concurrent/atomic/.*,
      java/util/jar/.*,
      java/util/logging/.*,
      java/util/prefs/.*,
      java/util/regex/.*,
      java/util/spi/.*,
      java/util/zip/.*,
      java/time/.*,
      javax/.*,
      sun/.*,
      sunw/.*,
      com/sun/.*,
      com/ibm/.*,
      com/apple/.*,
      com/oracle/.*,
      apple/.*,
      org/xml/.*,
      jdbm/.*,
      org/netbeans/.*,
      org/openide/.*,
      org/apache/xerces/.*,
      dalvik/.*,
      apple/.*,
      jdk/.*,
      org/omg/.*,
      org/w3c/.*,
      org/apache/lucene/util/packed/BulkOperationPacked.*,
      javafx/.*,
      org/jcp/.*,
      oracle/jrockit/.*
    
